### ISSUE TITLE
Add error message when you use wrong path

### ISSUE THREAD

**Issue by westscz** [weclaw1/inbac#14]
When I run the application with not existing directory, app just pop out, exit and send exception to terminal

Traceback:
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jarek/Downloads/Archives/inbac-master/inbac/inbac.py", line 34, in main
    app = Application(args.parse_arguments(), master=root)
  File "/home/jarek/Downloads/Archives/inbac-master/inbac/inbac.py", line 24, in __init__
    os.makedirs(args.output_dir)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/user'
```

In another case application just created directory and do nothing.

How reproduce this?

- Run application with path where you doesn't have permission to create directories
- Run application with path to folder which doesn't exist but in path where you have permission to create

**Comment by weclaw1** [comment]
I have added a message box with error message and file dialog asking for new output directory if you don't have permission to create output directory.

I'm also currently working on adding a menu where user will be able to change settings and input and output directory so if the input directory doesn't have any images you will be able to change it from the menu.
